//
// Generated by Bluespec Compiler, version 2012.09.beta1 (build 29570, 2012-09.11)
//
// On Tue Oct 16 11:00:14 EDT 2012
//
// Method conflict info:
// Method: ingress_put
// Conflict-free: egress_get
// Conflicts: ingress_put
//
// Method: egress_get
// Conflict-free: ingress_put
// Conflicts: egress_get
//
//
// Ports:
// Name                         I/O  size props
// RDY_ingress_put                O     1 reg
// egress_get                     O    33 reg
// RDY_egress_get                 O     1 reg
// CLK                            I     1 clock
// RST_N                          I     1 reset
// ingress_put                    I    33 reg
// EN_ingress_put                 I     1
// EN_egress_get                  I     1
//
// No combinational paths from inputs to outputs
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkFHSender(CLK,
		  RST_N,

		  ingress_put,
		  EN_ingress_put,
		  RDY_ingress_put,

		  EN_egress_get,
		  egress_get,
		  RDY_egress_get);
  input  CLK;
  input  RST_N;

  // action method ingress_put
  input  [32 : 0] ingress_put;
  input  EN_ingress_put;
  output RDY_ingress_put;

  // actionvalue method egress_get
  input  EN_egress_get;
  output [32 : 0] egress_get;
  output RDY_egress_get;

  // signals for module outputs
  wire [32 : 0] egress_get;
  wire RDY_egress_get, RDY_ingress_put;

  // register fhV
  reg [32 : 0] fhV;
  wire [32 : 0] fhV$D_IN;
  wire fhV$EN;

  // register fhV_1
  reg [32 : 0] fhV_1;
  wire [32 : 0] fhV_1$D_IN;
  wire fhV_1$EN;

  // register fhV_2
  reg [32 : 0] fhV_2;
  wire [32 : 0] fhV_2$D_IN;
  wire fhV_2$EN;

  // register fhp
  reg [3 : 0] fhp;
  wire [3 : 0] fhp$D_IN;
  wire fhp$EN;

  // register frmHeadLen
  reg [3 : 0] frmHeadLen;
  wire [3 : 0] frmHeadLen$D_IN;
  wire frmHeadLen$EN;

  // register sentFrmHead
  reg sentFrmHead;
  wire sentFrmHead$D_IN, sentFrmHead$EN;

  // register updateFH
  reg updateFH;
  wire updateFH$D_IN, updateFH$EN;

  // ports of submodule headerF
  wire headerF$CLR, headerF$DEQ, headerF$EMPTY_N, headerF$ENQ, headerF$FULL_N;

  // ports of submodule mesgInF
  wire [32 : 0] mesgInF$D_IN, mesgInF$D_OUT;
  wire mesgInF$CLR, mesgInF$DEQ, mesgInF$EMPTY_N, mesgInF$ENQ, mesgInF$FULL_N;

  // ports of submodule mesgOutF
  wire [32 : 0] mesgOutF$D_IN, mesgOutF$D_OUT;
  wire mesgOutF$CLR,
       mesgOutF$DEQ,
       mesgOutF$EMPTY_N,
       mesgOutF$ENQ,
       mesgOutF$FULL_N;

  // rule scheduling signals
  wire CAN_FIRE_RL_popFhV,
       CAN_FIRE_RL_sndHead,
       CAN_FIRE_RL_sndMesg,
       CAN_FIRE_egress_get,
       CAN_FIRE_ingress_put,
       WILL_FIRE_RL_popFhV,
       WILL_FIRE_RL_sndHead,
       WILL_FIRE_RL_sndMesg,
       WILL_FIRE_egress_get,
       WILL_FIRE_ingress_put;

  // inputs to muxes for submodule ports
  reg [32 : 0] MUX_mesgOutF$enq_1__VAL_1;

  // remaining internal signals
  wire fhp_EQ_frmHeadLen___d49;

  // action method ingress_put
  assign RDY_ingress_put = mesgInF$FULL_N ;
  assign CAN_FIRE_ingress_put = mesgInF$FULL_N ;
  assign WILL_FIRE_ingress_put = EN_ingress_put ;

  // actionvalue method egress_get
  assign egress_get = mesgOutF$D_OUT ;
  assign RDY_egress_get = mesgOutF$EMPTY_N ;
  assign CAN_FIRE_egress_get = mesgOutF$EMPTY_N ;
  assign WILL_FIRE_egress_get = EN_egress_get ;

  // submodule headerF
  FIFO20 #(.guarded(32'd1)) headerF(.RST(RST_N),
				    .CLK(CLK),
				    .ENQ(headerF$ENQ),
				    .DEQ(headerF$DEQ),
				    .CLR(headerF$CLR),
				    .FULL_N(headerF$FULL_N),
				    .EMPTY_N(headerF$EMPTY_N));

  // submodule mesgInF
  FIFO2 #(.width(32'd33), .guarded(32'd1)) mesgInF(.RST(RST_N),
						   .CLK(CLK),
						   .D_IN(mesgInF$D_IN),
						   .ENQ(mesgInF$ENQ),
						   .DEQ(mesgInF$DEQ),
						   .CLR(mesgInF$CLR),
						   .D_OUT(mesgInF$D_OUT),
						   .FULL_N(mesgInF$FULL_N),
						   .EMPTY_N(mesgInF$EMPTY_N));

  // submodule mesgOutF
  FIFO2 #(.width(32'd33), .guarded(32'd1)) mesgOutF(.RST(RST_N),
						    .CLK(CLK),
						    .D_IN(mesgOutF$D_IN),
						    .ENQ(mesgOutF$ENQ),
						    .DEQ(mesgOutF$DEQ),
						    .CLR(mesgOutF$CLR),
						    .D_OUT(mesgOutF$D_OUT),
						    .FULL_N(mesgOutF$FULL_N),
						    .EMPTY_N(mesgOutF$EMPTY_N));

  // rule RL_popFhV
  assign CAN_FIRE_RL_popFhV = headerF$FULL_N && updateFH ;
  assign WILL_FIRE_RL_popFhV = CAN_FIRE_RL_popFhV ;

  // rule RL_sndHead
  assign CAN_FIRE_RL_sndHead =
	     mesgOutF$FULL_N && headerF$EMPTY_N && !sentFrmHead ;
  assign WILL_FIRE_RL_sndHead = CAN_FIRE_RL_sndHead && !WILL_FIRE_RL_popFhV ;

  // rule RL_sndMesg
  assign CAN_FIRE_RL_sndMesg =
	     mesgOutF$FULL_N && mesgInF$EMPTY_N && sentFrmHead ;
  assign WILL_FIRE_RL_sndMesg = CAN_FIRE_RL_sndMesg ;

  // inputs to muxes for submodule ports
  always@(fhp or fhV_2 or fhV or fhV_1)
  begin
    case (fhp)
      4'd1: MUX_mesgOutF$enq_1__VAL_1 = fhV;
      4'd2: MUX_mesgOutF$enq_1__VAL_1 = fhV_1;
      default: MUX_mesgOutF$enq_1__VAL_1 =
		   { fhp != 4'd3 || fhV_2[32], fhV_2[31:0] };
    endcase
  end

  // register fhV
  assign fhV$D_IN = 33'd10 ;
  assign fhV$EN = CAN_FIRE_RL_popFhV ;

  // register fhV_1
  assign fhV_1$D_IN = 33'd11 ;
  assign fhV_1$EN = CAN_FIRE_RL_popFhV ;

  // register fhV_2
  assign fhV_2$D_IN = 33'd12 ;
  assign fhV_2$EN = CAN_FIRE_RL_popFhV ;

  // register fhp
  assign fhp$D_IN = fhp_EQ_frmHeadLen___d49 ? 4'd1 : fhp + 4'd1 ;
  assign fhp$EN = WILL_FIRE_RL_sndHead ;

  // register frmHeadLen
  assign frmHeadLen$D_IN = 4'h0 ;
  assign frmHeadLen$EN = 1'b0 ;

  // register sentFrmHead
  assign sentFrmHead$D_IN =
	     WILL_FIRE_RL_sndMesg ?
	       !mesgInF$D_OUT[32] :
	       fhp_EQ_frmHeadLen___d49 ;
  assign sentFrmHead$EN = WILL_FIRE_RL_sndMesg || WILL_FIRE_RL_sndHead ;

  // register updateFH
  assign updateFH$D_IN = WILL_FIRE_RL_sndHead && fhp_EQ_frmHeadLen___d49 ;
  assign updateFH$EN = WILL_FIRE_RL_sndHead || WILL_FIRE_RL_popFhV ;

  // submodule headerF
  assign headerF$ENQ = CAN_FIRE_RL_popFhV ;
  assign headerF$DEQ = WILL_FIRE_RL_sndHead && fhp_EQ_frmHeadLen___d49 ;
  assign headerF$CLR = 1'b0 ;

  // submodule mesgInF
  assign mesgInF$D_IN = ingress_put ;
  assign mesgInF$ENQ = EN_ingress_put ;
  assign mesgInF$DEQ = CAN_FIRE_RL_sndMesg ;
  assign mesgInF$CLR = 1'b0 ;

  // submodule mesgOutF
  assign mesgOutF$D_IN =
	     WILL_FIRE_RL_sndHead ?
	       MUX_mesgOutF$enq_1__VAL_1 :
	       mesgInF$D_OUT ;
  assign mesgOutF$ENQ = WILL_FIRE_RL_sndHead || WILL_FIRE_RL_sndMesg ;
  assign mesgOutF$DEQ = EN_egress_get ;
  assign mesgOutF$CLR = 1'b0 ;

  // remaining internal signals
  assign fhp_EQ_frmHeadLen___d49 = fhp == frmHeadLen ;

  // handling of inlined registers

  always@(posedge CLK)
  begin
    if (RST_N == `BSV_RESET_VALUE)
      begin
        fhp <= `BSV_ASSIGNMENT_DELAY 4'd1;
	frmHeadLen <= `BSV_ASSIGNMENT_DELAY 4'd3;
	sentFrmHead <= `BSV_ASSIGNMENT_DELAY 1'd0;
	updateFH <= `BSV_ASSIGNMENT_DELAY 1'd1;
      end
    else
      begin
        if (fhp$EN) fhp <= `BSV_ASSIGNMENT_DELAY fhp$D_IN;
	if (frmHeadLen$EN)
	  frmHeadLen <= `BSV_ASSIGNMENT_DELAY frmHeadLen$D_IN;
	if (sentFrmHead$EN)
	  sentFrmHead <= `BSV_ASSIGNMENT_DELAY sentFrmHead$D_IN;
	if (updateFH$EN) updateFH <= `BSV_ASSIGNMENT_DELAY updateFH$D_IN;
      end
    if (fhV$EN) fhV <= `BSV_ASSIGNMENT_DELAY fhV$D_IN;
    if (fhV_1$EN) fhV_1 <= `BSV_ASSIGNMENT_DELAY fhV_1$D_IN;
    if (fhV_2$EN) fhV_2 <= `BSV_ASSIGNMENT_DELAY fhV_2$D_IN;
  end

  // synopsys translate_off
  `ifdef BSV_NO_INITIAL_BLOCKS
  `else // not BSV_NO_INITIAL_BLOCKS
  initial
  begin
    fhV = 33'h0AAAAAAAA;
    fhV_1 = 33'h0AAAAAAAA;
    fhV_2 = 33'h0AAAAAAAA;
    fhp = 4'hA;
    frmHeadLen = 4'hA;
    sentFrmHead = 1'h0;
    updateFH = 1'h0;
  end
  `endif // BSV_NO_INITIAL_BLOCKS
  // synopsys translate_on
endmodule  // mkFHSender

