/*
 * Generated by Bluespec Compiler, version 2012.09.beta1 (build 29570, 2012-09.11)
 * 
 * On Thu Oct 11 17:17:19 EDT 2012
 * 
 */

/* Generation options: keep-fires */
#ifndef __mkMHSender_h__
#define __mkMHSender_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"


/* Class declaration for the mkMHSender module */
class MOD_mkMHSender : public Module {
 
 /* Clock handles */
 private:
  tClock __clk_handle_0;
 
 /* Clock gate handles */
 public:
  tUInt8 *clk_gate[0];
 
 /* Instantiation parameters */
 public:
 
 /* Module state */
 public:
  MOD_Reg<tUInt32> INST_fragLenCnt;
  MOD_Fifo<tUInt8> INST_headerF;
  MOD_Reg<tUInt32> INST_hp;
  MOD_Reg<tUInt32> INST_lenR;
  MOD_Fifo<tUInt32> INST_lengthF;
  MOD_Fifo<tUInt64> INST_mesgInF;
  MOD_Fifo<tUInt64> INST_mesgOutF;
  MOD_Fifo<tUInt8> INST_messageF;
  MOD_Reg<tUInt64> INST_mhV;
  MOD_Reg<tUInt64> INST_mhV_1;
  MOD_Reg<tUInt64> INST_mhV_2;
  MOD_Reg<tUInt64> INST_mhV_3;
  MOD_Reg<tUInt64> INST_mhV_4;
  MOD_Reg<tUInt64> INST_mhV_5;
  MOD_Fifo<tUInt8> INST_msgDoneF;
 
 /* Constructor */
 public:
  MOD_mkMHSender(tSimStateHdl simHdl, char const *name, Module *parent);
 
 /* Symbol init methods */
 private:
  void init_symbols_0();
 
 /* Reset signal definitions */
 private:
  tUInt8 PORT_RST_N;
 
 /* Port definitions */
 public:
  tUInt8 PORT_EN_src_get;
  tUInt8 PORT_EN_sink_put;
  tUInt8 PORT_EN_newLen_put;
  tUInt64 PORT_sink_put;
  tUInt32 PORT_newLen_put;
  tUInt64 PORT_src_get;
  tUInt8 PORT_RDY_src_get;
  tUInt8 PORT_RDY_sink_put;
  tUInt8 PORT_RDY_newLen_put;
  tUInt8 PORT_getLen_dwm;
  tUInt8 PORT_RDY_getLen_dwm;
 
 /* Publicly accessible definitions */
 public:
  tUInt8 DEF_WILL_FIRE_sink_put;
  tUInt8 DEF_WILL_FIRE_src_get;
  tUInt8 DEF_CAN_FIRE_sink_put;
  tUInt8 DEF_CAN_FIRE_src_get;
  tUInt8 DEF_WILL_FIRE_newLen_put;
  tUInt8 DEF_WILL_FIRE_RL_sndMesg;
  tUInt8 DEF_CAN_FIRE_RL_sndMesg;
  tUInt8 DEF_WILL_FIRE_RL_sndHead;
  tUInt8 DEF_CAN_FIRE_RL_sndHead;
  tUInt8 DEF_WILL_FIRE_RL_popMhV;
  tUInt8 DEF_CAN_FIRE_RL_popMhV;
  tUInt8 DEF_CAN_FIRE_getLen_dwm;
  tUInt8 DEF_CAN_FIRE_newLen_put;
 
 /* Local definitions */
 private:
  tUInt32 DEF_lenR___d67;
  tUInt32 DEF_b__h2474;
  tUInt8 DEF_fragLenCnt_9_EQ_IF_lenR_0_BIT_9_1_THEN_lenR_0__ETC___d76;
 
 /* Rules */
 public:
  void RL_popMhV();
  void RL_sndHead();
  void RL_sndMesg();
 
 /* Methods */
 public:
  tUInt64 METH_src_get();
  tUInt8 METH_RDY_src_get();
  void METH_sink_put(tUInt64 ARG_sink_put);
  tUInt8 METH_RDY_sink_put();
  void METH_newLen_put(tUInt32 ARG_newLen_put);
  tUInt8 METH_RDY_newLen_put();
  tUInt8 METH_getLen_dwm();
  tUInt8 METH_RDY_getLen_dwm();
 
 /* Reset routines */
 public:
  void reset_RST_N(tUInt8 ARG_rst_in);
 
 /* Static handles to reset routines */
 public:
 
 /* Pointers to reset fns in parent module for asserting output resets */
 private:
 
 /* Functions for the parent module to register its reset fns */
 public:
 
 /* Functions to set the elaborated clock id */
 public:
  void set_clk_0(char const *s);
 
 /* State dumping routine */
 public:
  void dump_state(unsigned int indent);
 
 /* VCD dumping routines */
 public:
  unsigned int dump_VCD_defs(unsigned int levels);
  void dump_VCD(tVCDDumpType dt, unsigned int levels, MOD_mkMHSender &backing);
  void vcd_defs(tVCDDumpType dt, MOD_mkMHSender &backing);
  void vcd_prims(tVCDDumpType dt, MOD_mkMHSender &backing);
};

#endif /* ifndef __mkMHSender_h__ */
