/*
 * Generated by Bluespec Compiler, version 2012.09.beta1 (build 29570, 2012-09.11)
 * 
 * On Sun Oct  7 15:17:28 EDT 2012
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkFTop_dp705.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkFTop_dp705::MODEL_mkFTop_dp705()
{
  mkFTop_dp705_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkFTop_dp705()
{
  MODEL_mkFTop_dp705 *model = new MODEL_mkFTop_dp705();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkFTop_dp705 &INST_top = *((MOD_mkFTop_dp705 *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d172;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d178;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d199;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d166;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d173;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d197;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d200;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d168;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d169;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d167;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d179;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d198;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d201;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d174;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d175;
	 tUInt32 DEF_INST_top_DEF_y__h3819;
	 tUInt32 DEF_INST_top_DEF_y__h9404;
	 tUInt8 DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d201;
	 tUInt8 DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d202;
	 tUInt32 DEF_INST_top_DEF_x__h3820;
	 tUInt32 DEF_INST_top_DEF_x__h9405;
	 INST_top.INST_buf1.PORT_EN_sink_put = (tUInt8)0u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_sink_put = (tUInt8)0u;
	 INST_top.INST_buf1.PORT_EN_src_get = (tUInt8)0u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_src_get = (tUInt8)0u;
	 INST_top.DEF_CAN_FIRE_RL_chk_cmpEOP__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_chk_cmpEOP__dreg_update = INST_top.DEF_CAN_FIRE_RL_chk_cmpEOP__dreg_update;
	 INST_top.DEF_CAN_FIRE_RL_chk_cmpFire__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_chk_cmpFire__dreg_update = INST_top.DEF_CAN_FIRE_RL_chk_cmpFire__dreg_update;
	 INST_top.DEF_CAN_FIRE_RL_chk_cmpMatch__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_chk_cmpMatch__dreg_update = INST_top.DEF_CAN_FIRE_RL_chk_cmpMatch__dreg_update;
	 INST_top.DEF_CAN_FIRE_RL_chk_compare = INST_top.INST_chk_buffF.METH_i_notEmpty() && INST_top.INST_chk_checkF.METH_i_notEmpty();
	 INST_top.DEF_WILL_FIRE_RL_chk_compare = INST_top.DEF_CAN_FIRE_RL_chk_compare;
	 INST_top.DEF_CAN_FIRE_RL_cycleCount = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_cycleCount = INST_top.DEF_CAN_FIRE_RL_cycleCount;
	 DEF_INST_top_DEF_x__h3820 = INST_top.INST_gen1_mesgLen.METH_read();
	 INST_top.DEF_x__h3818 = INST_top.INST_gen1_count.METH_read();
	 DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d201 = INST_top.INST_gen1_mesgOutF.METH_i_notFull();
	 DEF_INST_top_DEF_y__h3819 = 511u & (DEF_INST_top_DEF_x__h3820 - 1u);
	 INST_top.DEF_CAN_FIRE_RL_gen1_genMesgEOP = (DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d201 && INST_top.INST_gen1_randomF.METH_i_notEmpty()) && (INST_top.DEF_x__h3818) == DEF_INST_top_DEF_y__h3819;
	 INST_top.DEF_WILL_FIRE_RL_gen1_genMesgEOP = INST_top.DEF_CAN_FIRE_RL_gen1_genMesgEOP;
	 INST_top.DEF_CAN_FIRE_RL_gen1_genMesgNotEOP = DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d201 && (INST_top.DEF_x__h3818) < DEF_INST_top_DEF_y__h3819;
	 INST_top.DEF_WILL_FIRE_RL_gen1_genMesgNotEOP = INST_top.DEF_CAN_FIRE_RL_gen1_genMesgNotEOP;
	 INST_top.DEF_CAN_FIRE_RL_gen1_setMsgLen = INST_top.INST_gen1_randomF.METH_i_notFull() && INST_top.INST_gen1_startLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen1_setMsgLen = INST_top.DEF_CAN_FIRE_RL_gen1_setMsgLen;
	 INST_top.DEF_CAN_FIRE_RL_gen1_setupLFSR = INST_top.INST_gen1_seedLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen1_setupLFSR = INST_top.DEF_CAN_FIRE_RL_gen1_setupLFSR;
	 DEF_INST_top_DEF_x__h9405 = INST_top.INST_gen2_mesgLen.METH_read();
	 INST_top.DEF_x__h9403 = INST_top.INST_gen2_count.METH_read();
	 DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d202 = INST_top.INST_gen2_mesgOutF.METH_i_notFull();
	 DEF_INST_top_DEF_y__h9404 = 511u & (DEF_INST_top_DEF_x__h9405 - 1u);
	 INST_top.DEF_CAN_FIRE_RL_gen2_genMesgEOP = (DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d202 && INST_top.INST_gen2_randomF.METH_i_notEmpty()) && (INST_top.DEF_x__h9403) == DEF_INST_top_DEF_y__h9404;
	 INST_top.DEF_WILL_FIRE_RL_gen2_genMesgEOP = INST_top.DEF_CAN_FIRE_RL_gen2_genMesgEOP;
	 INST_top.DEF_CAN_FIRE_RL_gen2_genMesgNotEOP = DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d202 && (INST_top.DEF_x__h9403) < DEF_INST_top_DEF_y__h9404;
	 INST_top.DEF_WILL_FIRE_RL_gen2_genMesgNotEOP = INST_top.DEF_CAN_FIRE_RL_gen2_genMesgNotEOP;
	 INST_top.DEF_CAN_FIRE_RL_gen2_setupLFSR = INST_top.INST_gen2_seedLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen2_setupLFSR = INST_top.DEF_CAN_FIRE_RL_gen2_setupLFSR;
	 INST_top.DEF_CAN_FIRE_RL_gen2_setMsgLen = INST_top.INST_gen2_randomF.METH_i_notFull() && INST_top.INST_gen2_startLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen2_setMsgLen = INST_top.DEF_CAN_FIRE_RL_gen2_setMsgLen;
	 INST_top.DEF_CAN_FIRE_RL_gobble = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_gobble = INST_top.DEF_CAN_FIRE_RL_gobble;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut = INST_top.INST_buf1.METH_RDY_sink_put() && INST_top.INST_gen1_mesgOutF.METH_i_notEmpty();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_1 = INST_top.INST_buf1.METH_RDY_src_get() && INST_top.INST_chk_buffF.METH_i_notFull();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_1 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_1;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_2 = INST_top.INST_gen2_mesgOutF.METH_i_notEmpty() && INST_top.INST_chk_checkF.METH_i_notFull();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_2 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_2;
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_s1___d188 = INST_top.INST_buf1.INST_bram_serverAdapterA_s1.METH_read();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d173 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_notFull();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d172 = (tUInt8)((INST_top.INST_buf1.DEF_bram_serverAdapterA_s1___d188) >> 1u);
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_moveToOutFIFO = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d173 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d172;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_moveToOutFIFO = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_moveToOutFIFO;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d200 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_i_notEmpty();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d166 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_notEmpty();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstCore = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d200 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d166;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstCore = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstCore;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_overRun = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d172 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d173;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_overRun = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_overRun;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_s1__dreg_update = (tUInt8)1u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_s1__dreg_update = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_s1__dreg_update;
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_s1___d189 = INST_top.INST_buf1.INST_bram_serverAdapterB_s1.METH_read();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d179 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_notFull();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d178 = (tUInt8)((INST_top.INST_buf1.DEF_bram_serverAdapterB_s1___d189) >> 1u);
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_moveToOutFIFO = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d179 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d178;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_moveToOutFIFO = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_moveToOutFIFO;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d201 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_i_notEmpty();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d167 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_notEmpty();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstCore = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d201 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d167;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstCore = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstCore;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d178 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d179;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_overRun = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_s1__dreg_update = (tUInt8)1u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_s1__dreg_update = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_s1__dreg_update;
	 INST_top.INST_buf1.DEF_b__h2917 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt.METH_read();
	 DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d199 = INST_top.INST_buf1.INST_msgF.METH_i_notEmpty();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_readReqBRAM = (DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d199 && primSLT8(1u,
															  3u,
															  (tUInt8)(INST_top.INST_buf1.DEF_b__h2917),
															  3u,
															  (tUInt8)3u)) && INST_top.INST_buf1.INST_msgF.METH_notEmpty();
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_readReqBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_readReqBRAM;
	 INST_top.INST_buf1.DEF_b__h1512 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt.METH_read();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_writeBRAM = INST_top.INST_buf1.INST_mesgInF.METH_i_notEmpty() && (primSLT8(1u,
														       3u,
														       (tUInt8)(INST_top.INST_buf1.DEF_b__h1512),
														       3u,
														       (tUInt8)3u) && INST_top.INST_buf1.INST_msgF.METH_i_notFull());
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_writeBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_writeBRAM;
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_genMesgEOP)
	   INST_top.RL_gen1_genMesgEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_genMesgNotEOP)
	   INST_top.RL_gen1_genMesgNotEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_setMsgLen)
	   INST_top.RL_gen1_setMsgLen();
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_setupLFSR)
	   INST_top.RL_gen1_setupLFSR();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_genMesgEOP)
	   INST_top.RL_gen2_genMesgEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_genMesgNotEOP)
	   INST_top.RL_gen2_genMesgNotEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_setMsgLen)
	   INST_top.RL_gen2_setMsgLen();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_setupLFSR)
	   INST_top.RL_gen2_setupLFSR();
	 if (INST_top.DEF_WILL_FIRE_RL_gobble)
	   INST_top.RL_gobble();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_compare)
	   INST_top.RL_chk_compare();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_cmpEOP__dreg_update)
	   INST_top.RL_chk_cmpEOP__dreg_update();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_cmpFire__dreg_update)
	   INST_top.RL_chk_cmpFire__dreg_update();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_cmpMatch__dreg_update)
	   INST_top.RL_chk_cmpMatch__dreg_update();
	 if (INST_top.DEF_WILL_FIRE_RL_cycleCount)
	   INST_top.RL_cycleCount();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut)
	   INST_top.RL_mkConnectionGetPut();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_1)
	   INST_top.RL_mkConnectionGetPut_1();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_2)
	   INST_top.RL_mkConnectionGetPut_2();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_moveToOutFIFO)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_moveToOutFIFO();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d169 = INST_top.INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.METH_whas();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d168 = INST_top.INST_buf1.INST_bram_serverAdapterA_outData_enqData.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_deqOnly = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d200 && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d169 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d168);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_deqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_deqOnly;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d197 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_i_notFull();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d200 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d197) && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d169 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d168);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqOnly = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d197 && (!DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d169 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d168);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqOnly;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq = !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d166 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d168;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstCore)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_setFirstCore();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_enqAndDeq();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_setFirstEnq();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_enqOnly();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_overRun)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_overRun();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_deqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_deqOnly();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_moveToOutFIFO)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_moveToOutFIFO();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d174 = INST_top.INST_buf1.INST_bram_serverAdapterB_outData_enqData.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq = !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d167 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d174;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstCore)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_setFirstCore();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_setFirstEnq();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_readBRAM = DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d199 && ((DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d167 || DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d174) && (INST_top.INST_buf1.INST_mesgOutF.METH_i_notFull() && INST_top.INST_buf1.INST_bram_serverAdapterB_outData_outData.METH_whas()));
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_readBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_readBRAM;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_overRun)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_overRun();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_readReqBRAM)
	   INST_top.INST_buf1.RL_readReqBRAM();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways = INST_top.INST_buf1.INST_bram_serverAdapterB_writeWithResp.METH_whas();
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_stageReadResponseAlways();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_s1__dreg_update)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_s1__dreg_update();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_readBRAM)
	   INST_top.INST_buf1.RL_readBRAM();
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_3_whas____d186 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_3.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_2_whas____d177 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_2.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_1_whas____d176 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_1.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_cnt_finalAdd = (INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_1_whas____d176 || INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_2_whas____d177) || INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_3_whas____d186;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_cnt_finalAdd = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_cnt_finalAdd;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d175 = INST_top.INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_deqOnly = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d201 && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d175 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d174)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_deqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_deqOnly;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d198 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_i_notFull();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq = ((DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d201 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d198) && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d175 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d174)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq || INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqOnly = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d198 && (!DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d175 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d174)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqOnly;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_cnt_finalAdd)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_cnt_finalAdd();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_deqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_deqOnly();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_enqAndDeq();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_writeBRAM)
	   INST_top.INST_buf1.RL_writeBRAM();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways = INST_top.INST_buf1.INST_bram_serverAdapterA_writeWithResp.METH_whas();
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_stageReadResponseAlways();
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_3_whas____d184 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_3.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_2_whas____d171 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_2.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_1_whas____d170 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_1.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_cnt_finalAdd = (INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_1_whas____d170 || INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_2_whas____d171) || INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_3_whas____d184;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_cnt_finalAdd = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_cnt_finalAdd;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_cnt_finalAdd)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_cnt_finalAdd();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_s1__dreg_update)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_s1__dreg_update();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_enqOnly();
	 INST_top.INST_chk_cmpMatch_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_chk_cmpEOP_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_chk_cmpFire_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_s1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_s1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_memory.clkA((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_memory.clkB((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_buf1.INST_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_mesgInF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_msgF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_countWrd.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_countRdReq.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_countRd.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_readAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_writeAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterA_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterA_s1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterB_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterB_s1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen1_randomF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen1_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_patternV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_mesgLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_initV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_tmp.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_lfsr_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_seedLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_startLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_minLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_maxLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen2_randomF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen2_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_patternV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_mesgLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_initV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_tmp.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_lfsr_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_seedLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_startLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_minLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_maxLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_buffF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_chk_incorrect.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_checkF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_chk_minLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_maxLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_mesgCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_wordCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_buff.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_check.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_cmpFire.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_cmpEOP.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_cmpMatch.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cycleCounter.rst_tick__clk__1((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkFTop_dp705::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkFTop_dp705_instance = new MOD_mkFTop_dp705(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkFTop_dp705_instance->INST_gen1_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_gen1_randomF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_gen2_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_gen2_randomF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_buffF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_checkF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_cmpFire_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_cmpEOP_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_cmpMatch_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_mesgInF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_msgF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_memory.set_clk_1)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_memory.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outDataCore.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_enqData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_outData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_2.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_3.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_writeWithResp.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_s1_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outDataCore.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_enqData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_outData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_2.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_3.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_writeWithResp.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_s1_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->set_clk_0)("CLK");
}
void MODEL_mkFTop_dp705::destroy_model()
{
  delete mkFTop_dp705_instance;
  mkFTop_dp705_instance = NULL;
}
void MODEL_mkFTop_dp705::reset_model(bool asserted)
{
  (mkFTop_dp705_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkFTop_dp705::get_instance()
{
  return mkFTop_dp705_instance;
}

/* Fill in version numbers */
void MODEL_mkFTop_dp705::get_version(unsigned int *year,
				     unsigned int *month,
				     char const **annotation,
				     char const **build)
{
  *year = 2012u;
  *month = 9u;
  *annotation = "beta1";
  *build = "29570";
}

/* Get the model creation time */
time_t MODEL_mkFTop_dp705::get_creation_time()
{
  
  /* Sun Oct  7 19:17:28 UTC 2012 */
  return 1349637448llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkFTop_dp705::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkFTop_dp705::dump_state()
{
  (mkFTop_dp705_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkFTop_dp705 & mkFTop_dp705_backing(tSimStateHdl simHdl)
{
  static MOD_mkFTop_dp705 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkFTop_dp705(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkFTop_dp705::dump_VCD_defs()
{
  (mkFTop_dp705_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkFTop_dp705::dump_VCD(tVCDDumpType dt)
{
  (mkFTop_dp705_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkFTop_dp705_backing(sim_hdl));
}
