/*
 * Generated by Bluespec Compiler, version 2012.09.beta1 (build 29570, 2012-09.11)
 * 
 * On Thu Oct 11 17:17:19 EDT 2012
 * 
 */
#include "bluesim_primitives.h"
#include "model_mkFTop_dp705.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"


/* Constructor */
MODEL_mkFTop_dp705::MODEL_mkFTop_dp705()
{
  mkFTop_dp705_instance = NULL;
}

/* Function for creating a new model */
void * new_MODEL_mkFTop_dp705()
{
  MODEL_mkFTop_dp705 *model = new MODEL_mkFTop_dp705();
  return (void *)(model);
}

/* Schedule functions */

static void schedule_posedge_CLK(tSimStateHdl simHdl, void *instance_ptr)
       {
	 MOD_mkFTop_dp705 &INST_top = *((MOD_mkFTop_dp705 *)(instance_ptr));
	 tUInt8 DEF_INST_top_INST_mhrcv_DEF_mesgInF_i_notEmpty____d44;
	 tUInt8 DEF_INST_top_INST_mhsnd_DEF_mesgOutF_i_notFull____d75;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_0_BIT_1___d190;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_17_BIT_1___d196;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d183;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d191;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d213;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d216;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d186;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d187;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d184;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d197;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d214;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d217;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d192;
	 tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d193;
	 tUInt32 DEF_INST_top_DEF_y__h3819;
	 tUInt32 DEF_INST_top_DEF_y__h9404;
	 tUInt8 DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d210;
	 tUInt8 DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d224;
	 tUInt32 DEF_INST_top_DEF_x__h3820;
	 tUInt32 DEF_INST_top_DEF_x__h9405;
	 INST_top.INST_buf1.PORT_EN_sink_put = (tUInt8)0u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_sink_put = (tUInt8)0u;
	 INST_top.INST_buf1.PORT_EN_src_get = (tUInt8)0u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_src_get = (tUInt8)0u;
	 INST_top.INST_mhsnd.PORT_EN_sink_put = (tUInt8)0u;
	 INST_top.INST_mhsnd.DEF_WILL_FIRE_sink_put = (tUInt8)0u;
	 INST_top.INST_mhrcv.PORT_EN_sink_put = (tUInt8)0u;
	 INST_top.INST_mhrcv.DEF_WILL_FIRE_sink_put = (tUInt8)0u;
	 INST_top.INST_mhsnd.PORT_EN_src_get = (tUInt8)0u;
	 INST_top.INST_mhsnd.DEF_WILL_FIRE_src_get = (tUInt8)0u;
	 INST_top.INST_mhrcv.PORT_EN_src_get = (tUInt8)0u;
	 INST_top.INST_mhrcv.DEF_WILL_FIRE_src_get = (tUInt8)0u;
	 INST_top.INST_buf1.PORT_EN_length_dwm = (tUInt8)0u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_length_dwm = (tUInt8)0u;
	 INST_top.INST_buf1.PORT_EN_newLen_get = (tUInt8)0u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_newLen_get = (tUInt8)0u;
	 INST_top.INST_mhsnd.PORT_EN_newLen_put = (tUInt8)0u;
	 INST_top.INST_mhsnd.DEF_WILL_FIRE_newLen_put = (tUInt8)0u;
	 INST_top.DEF_CAN_FIRE_RL_chk_cmpEOP__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_chk_cmpEOP__dreg_update = INST_top.DEF_CAN_FIRE_RL_chk_cmpEOP__dreg_update;
	 INST_top.DEF_CAN_FIRE_RL_chk_cmpFire__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_chk_cmpFire__dreg_update = INST_top.DEF_CAN_FIRE_RL_chk_cmpFire__dreg_update;
	 INST_top.DEF_CAN_FIRE_RL_chk_cmpMatch__dreg_update = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_chk_cmpMatch__dreg_update = INST_top.DEF_CAN_FIRE_RL_chk_cmpMatch__dreg_update;
	 INST_top.DEF_CAN_FIRE_RL_chk_compare = INST_top.INST_chk_buffF.METH_i_notEmpty() && INST_top.INST_chk_checkF.METH_i_notEmpty();
	 INST_top.DEF_WILL_FIRE_RL_chk_compare = INST_top.DEF_CAN_FIRE_RL_chk_compare;
	 INST_top.DEF_CAN_FIRE_RL_cnctDwm = INST_top.INST_buf1.METH_RDY_length_dwm() && INST_top.INST_mhsnd.METH_getLen_dwm();
	 INST_top.DEF_WILL_FIRE_RL_cnctDwm = INST_top.DEF_CAN_FIRE_RL_cnctDwm;
	 DEF_INST_top_DEF_x__h3820 = INST_top.INST_gen1_mesgLen.METH_read();
	 INST_top.DEF_x__h3818 = INST_top.INST_gen1_count.METH_read();
	 DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d210 = INST_top.INST_gen1_mesgOutF.METH_i_notFull();
	 DEF_INST_top_DEF_y__h3819 = 511u & (DEF_INST_top_DEF_x__h3820 - 1u);
	 INST_top.DEF_CAN_FIRE_RL_gen1_genMesgEOP = (DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d210 && INST_top.INST_gen1_randomF.METH_i_notEmpty()) && (INST_top.DEF_x__h3818) == DEF_INST_top_DEF_y__h3819;
	 INST_top.DEF_WILL_FIRE_RL_gen1_genMesgEOP = INST_top.DEF_CAN_FIRE_RL_gen1_genMesgEOP;
	 INST_top.DEF_CAN_FIRE_RL_cycleCount = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_cycleCount = INST_top.DEF_CAN_FIRE_RL_cycleCount;
	 INST_top.DEF_CAN_FIRE_RL_gen1_genMesgNotEOP = DEF_INST_top_DEF_gen1_mesgOutF_i_notFull____d210 && (INST_top.DEF_x__h3818) < DEF_INST_top_DEF_y__h3819;
	 INST_top.DEF_WILL_FIRE_RL_gen1_genMesgNotEOP = INST_top.DEF_CAN_FIRE_RL_gen1_genMesgNotEOP;
	 INST_top.DEF_CAN_FIRE_RL_gen1_setMsgLen = INST_top.INST_gen1_randomF.METH_i_notFull() && INST_top.INST_gen1_startLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen1_setMsgLen = INST_top.DEF_CAN_FIRE_RL_gen1_setMsgLen;
	 INST_top.DEF_CAN_FIRE_RL_gen1_setupLFSR = INST_top.INST_gen1_seedLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen1_setupLFSR = INST_top.DEF_CAN_FIRE_RL_gen1_setupLFSR;
	 DEF_INST_top_DEF_x__h9405 = INST_top.INST_gen2_mesgLen.METH_read();
	 INST_top.DEF_x__h9403 = INST_top.INST_gen2_count.METH_read();
	 DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d224 = INST_top.INST_gen2_mesgOutF.METH_i_notFull();
	 DEF_INST_top_DEF_y__h9404 = 511u & (DEF_INST_top_DEF_x__h9405 - 1u);
	 INST_top.DEF_CAN_FIRE_RL_gen2_genMesgEOP = (DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d224 && INST_top.INST_gen2_randomF.METH_i_notEmpty()) && (INST_top.DEF_x__h9403) == DEF_INST_top_DEF_y__h9404;
	 INST_top.DEF_WILL_FIRE_RL_gen2_genMesgEOP = INST_top.DEF_CAN_FIRE_RL_gen2_genMesgEOP;
	 INST_top.DEF_CAN_FIRE_RL_gen2_setMsgLen = INST_top.INST_gen2_randomF.METH_i_notFull() && INST_top.INST_gen2_startLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen2_setMsgLen = INST_top.DEF_CAN_FIRE_RL_gen2_setMsgLen;
	 INST_top.DEF_CAN_FIRE_RL_gen2_genMesgNotEOP = DEF_INST_top_DEF_gen2_mesgOutF_i_notFull____d224 && (INST_top.DEF_x__h9403) < DEF_INST_top_DEF_y__h9404;
	 INST_top.DEF_WILL_FIRE_RL_gen2_genMesgNotEOP = INST_top.DEF_CAN_FIRE_RL_gen2_genMesgNotEOP;
	 INST_top.DEF_CAN_FIRE_RL_gen2_setupLFSR = INST_top.INST_gen2_seedLFSR.METH_read();
	 INST_top.DEF_WILL_FIRE_RL_gen2_setupLFSR = INST_top.DEF_CAN_FIRE_RL_gen2_setupLFSR;
	 INST_top.DEF_CAN_FIRE_RL_gobble = (tUInt8)1u;
	 INST_top.DEF_WILL_FIRE_RL_gobble = INST_top.DEF_CAN_FIRE_RL_gobble;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut = INST_top.INST_buf1.METH_RDY_sink_put() && INST_top.INST_gen1_mesgOutF.METH_i_notEmpty();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_1 = INST_top.INST_mhsnd.METH_RDY_newLen_put() && INST_top.INST_buf1.METH_RDY_newLen_get();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_1 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_1;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_2 = INST_top.INST_mhsnd.METH_RDY_sink_put() && INST_top.INST_buf1.METH_RDY_src_get();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_2 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_2;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_4 = INST_top.INST_mhrcv.METH_RDY_sink_put() && INST_top.INST_s2rF.METH_i_notEmpty();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_4 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_4;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_3 = INST_top.INST_mhsnd.METH_RDY_src_get() && INST_top.INST_s2rF.METH_i_notFull();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_3 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_3;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_5 = INST_top.INST_mhrcv.METH_RDY_src_get() && INST_top.INST_chk_buffF.METH_i_notFull();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_5 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_5;
	 INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_6 = INST_top.INST_gen2_mesgOutF.METH_i_notEmpty() && INST_top.INST_chk_checkF.METH_i_notFull();
	 INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_6 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_6;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_accum_accumulate = (tUInt8)1u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_accum_accumulate = INST_top.INST_buf1.DEF_CAN_FIRE_RL_accum_accumulate;
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_s1___d204 = INST_top.INST_buf1.INST_bram_serverAdapterA_s1.METH_read();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d191 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_notFull();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_0_BIT_1___d190 = (tUInt8)((INST_top.INST_buf1.DEF_bram_serverAdapterA_s1___d204) >> 1u);
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_moveToOutFIFO = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d191 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_0_BIT_1___d190;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_moveToOutFIFO = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_moveToOutFIFO;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d216 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_i_notEmpty();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d183 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_notEmpty();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstCore = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d216 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d183;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstCore = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstCore;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_overRun = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_0_BIT_1___d190 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d191;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_overRun = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_overRun;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_s1__dreg_update = (tUInt8)1u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_s1__dreg_update = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_s1__dreg_update;
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_s1___d205 = INST_top.INST_buf1.INST_bram_serverAdapterB_s1.METH_read();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d197 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_notFull();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_17_BIT_1___d196 = (tUInt8)((INST_top.INST_buf1.DEF_bram_serverAdapterB_s1___d205) >> 1u);
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_moveToOutFIFO = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d197 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_17_BIT_1___d196;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_moveToOutFIFO = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_moveToOutFIFO;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d217 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_i_notEmpty();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d184 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_notEmpty();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstCore = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d217 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d184;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstCore = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstCore;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_17_BIT_1___d196 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d197;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_overRun = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_s1__dreg_update = (tUInt8)1u;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_s1__dreg_update = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_s1__dreg_update;
	 INST_top.INST_buf1.DEF_msgF_i_notEmpty____d215 = INST_top.INST_buf1.INST_msgF.METH_i_notEmpty();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_newLength = (INST_top.INST_buf1.DEF_msgF_i_notEmpty____d215 && INST_top.INST_buf1.INST_lenF.METH_i_notFull()) && INST_top.INST_buf1.INST_newMsg.METH_read();
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_newLength = INST_top.INST_buf1.DEF_CAN_FIRE_RL_newLength;
	 INST_top.INST_buf1.DEF_b__h4528 = INST_top.INST_buf1.INST_countRdReq.METH_read();
	 INST_top.INST_buf1.DEF_msgF_first____d179 = INST_top.INST_buf1.INST_msgF.METH_first();
	 INST_top.INST_buf1.DEF_x__h819 = INST_top.INST_buf1.INST_accum_value.METH_read();
	 INST_top.INST_buf1.DEF_b__h3340 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt.METH_read();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_readReqBRAM = (INST_top.INST_buf1.DEF_msgF_i_notEmpty____d215 && primSLT8(1u,
														      3u,
														      (tUInt8)(INST_top.INST_buf1.DEF_b__h3340),
														      3u,
														      (tUInt8)3u)) && ((INST_top.INST_buf1.DEF_b__h4528) < (INST_top.INST_buf1.DEF_msgF_first____d179) && !((INST_top.INST_buf1.DEF_x__h819) == (tUInt8)0u));
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_readReqBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_readReqBRAM;
	 INST_top.INST_buf1.DEF_b__h1935 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt.METH_read();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_writeBRAM = INST_top.INST_buf1.INST_mesgInF.METH_i_notEmpty() && (primSLT8(1u,
														       3u,
														       (tUInt8)(INST_top.INST_buf1.DEF_b__h1935),
														       3u,
														       (tUInt8)3u) && INST_top.INST_buf1.INST_msgF.METH_i_notFull());
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_writeBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_writeBRAM;
	 INST_top.INST_mhsnd.DEF_CAN_FIRE_RL_popMhV = (INST_top.INST_mhsnd.INST_lengthF.METH_i_notEmpty() && INST_top.INST_mhsnd.INST_headerF.METH_i_notFull()) && INST_top.INST_mhsnd.INST_lengthF.METH_notEmpty();
	 INST_top.INST_mhsnd.DEF_WILL_FIRE_RL_popMhV = INST_top.INST_mhsnd.DEF_CAN_FIRE_RL_popMhV;
	 DEF_INST_top_INST_mhrcv_DEF_mesgInF_i_notEmpty____d44 = INST_top.INST_mhrcv.INST_mesgInF.METH_i_notEmpty();
	 INST_top.INST_mhrcv.DEF_CAN_FIRE_RL_rcvHeader = (DEF_INST_top_INST_mhrcv_DEF_mesgInF_i_notEmpty____d44 && INST_top.INST_mhrcv.INST_messageF.METH_i_notFull()) && INST_top.INST_mhrcv.INST_endHead.METH_read();
	 INST_top.INST_mhrcv.DEF_WILL_FIRE_RL_rcvHeader = INST_top.INST_mhrcv.DEF_CAN_FIRE_RL_rcvHeader;
	 INST_top.INST_mhrcv.DEF_CAN_FIRE_RL_moveMessage = (DEF_INST_top_INST_mhrcv_DEF_mesgInF_i_notEmpty____d44 && (INST_top.INST_mhrcv.INST_mesgOutF.METH_i_notFull() && INST_top.INST_mhrcv.INST_messageF.METH_i_notEmpty())) && INST_top.INST_mhrcv.INST_messageF.METH_notEmpty();
	 INST_top.INST_mhrcv.DEF_WILL_FIRE_RL_moveMessage = INST_top.INST_mhrcv.DEF_CAN_FIRE_RL_moveMessage && !(INST_top.INST_mhrcv.DEF_WILL_FIRE_RL_rcvHeader);
	 DEF_INST_top_INST_mhsnd_DEF_mesgOutF_i_notFull____d75 = INST_top.INST_mhsnd.INST_mesgOutF.METH_i_notFull();
	 INST_top.INST_mhsnd.DEF_CAN_FIRE_RL_sndHead = (DEF_INST_top_INST_mhsnd_DEF_mesgOutF_i_notFull____d75 && (INST_top.INST_mhsnd.INST_headerF.METH_i_notEmpty() && INST_top.INST_mhsnd.INST_messageF.METH_i_notFull())) && INST_top.INST_mhsnd.INST_headerF.METH_notEmpty();
	 INST_top.INST_mhsnd.DEF_WILL_FIRE_RL_sndHead = INST_top.INST_mhsnd.DEF_CAN_FIRE_RL_sndHead;
	 INST_top.INST_mhsnd.DEF_CAN_FIRE_RL_sndMesg = (DEF_INST_top_INST_mhsnd_DEF_mesgOutF_i_notFull____d75 && (INST_top.INST_mhsnd.INST_mesgInF.METH_i_notEmpty() && INST_top.INST_mhsnd.INST_messageF.METH_i_notEmpty())) && INST_top.INST_mhsnd.INST_messageF.METH_notEmpty();
	 INST_top.INST_mhsnd.DEF_WILL_FIRE_RL_sndMesg = INST_top.INST_mhsnd.DEF_CAN_FIRE_RL_sndMesg && !(INST_top.INST_mhsnd.DEF_WILL_FIRE_RL_sndHead);
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_genMesgEOP)
	   INST_top.RL_gen1_genMesgEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_genMesgNotEOP)
	   INST_top.RL_gen1_genMesgNotEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_setMsgLen)
	   INST_top.RL_gen1_setMsgLen();
	 if (INST_top.DEF_WILL_FIRE_RL_gen1_setupLFSR)
	   INST_top.RL_gen1_setupLFSR();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_genMesgEOP)
	   INST_top.RL_gen2_genMesgEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_setMsgLen)
	   INST_top.RL_gen2_setMsgLen();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_genMesgNotEOP)
	   INST_top.RL_gen2_genMesgNotEOP();
	 if (INST_top.DEF_WILL_FIRE_RL_gen2_setupLFSR)
	   INST_top.RL_gen2_setupLFSR();
	 if (INST_top.DEF_WILL_FIRE_RL_gobble)
	   INST_top.RL_gobble();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_compare)
	   INST_top.RL_chk_compare();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_cmpEOP__dreg_update)
	   INST_top.RL_chk_cmpEOP__dreg_update();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_cmpFire__dreg_update)
	   INST_top.RL_chk_cmpFire__dreg_update();
	 if (INST_top.DEF_WILL_FIRE_RL_chk_cmpMatch__dreg_update)
	   INST_top.RL_chk_cmpMatch__dreg_update();
	 if (INST_top.DEF_WILL_FIRE_RL_cycleCount)
	   INST_top.RL_cycleCount();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut)
	   INST_top.RL_mkConnectionGetPut();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_2)
	   INST_top.RL_mkConnectionGetPut_2();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_4)
	   INST_top.RL_mkConnectionGetPut_4();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_3)
	   INST_top.RL_mkConnectionGetPut_3();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_5)
	   INST_top.RL_mkConnectionGetPut_5();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_6)
	   INST_top.RL_mkConnectionGetPut_6();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_moveToOutFIFO)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_moveToOutFIFO();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d187 = INST_top.INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.METH_whas();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d186 = INST_top.INST_buf1.INST_bram_serverAdapterA_outData_enqData.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_deqOnly = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d216 && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d187 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d186);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_deqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_deqOnly;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d213 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_i_notFull();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d216 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d213) && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d187 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d186);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqOnly = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d213 && (!DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d187 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d186);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqOnly;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq = !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d183 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d186;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstCore)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_setFirstCore();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_enqAndDeq();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_setFirstEnq();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_enqOnly();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_overRun)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_overRun();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_deqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_outData_deqOnly();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_moveToOutFIFO)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_moveToOutFIFO();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d192 = INST_top.INST_buf1.INST_bram_serverAdapterB_outData_enqData.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq = !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d184 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d192;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstCore)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_setFirstCore();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_setFirstEnq();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_readBRAM = INST_top.INST_buf1.DEF_msgF_i_notEmpty____d215 && ((DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d184 || DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d192) && (INST_top.INST_buf1.INST_mesgOutF.METH_i_notFull() && INST_top.INST_buf1.INST_bram_serverAdapterB_outData_outData.METH_whas()));
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_readBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_readBRAM;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_overRun)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_overRun();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_newLength)
	   INST_top.INST_buf1.RL_newLength();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_readBRAM)
	   INST_top.INST_buf1.RL_readBRAM();
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d193 = INST_top.INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_deqOnly = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d217 && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d193 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d192)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_deqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_deqOnly;
	 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d214 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_i_notFull();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq = ((DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d217 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d214) && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d193 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d192)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq || INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq;
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqOnly = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d214 && (!DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d193 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d192)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun);
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqOnly;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_deqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_deqOnly();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_enqAndDeq();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqOnly)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_outData_enqOnly();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_readReqBRAM)
	   INST_top.INST_buf1.RL_readReqBRAM();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways = INST_top.INST_buf1.INST_bram_serverAdapterB_writeWithResp.METH_whas();
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways;
	 if (INST_top.DEF_WILL_FIRE_RL_cnctDwm)
	   INST_top.RL_cnctDwm();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_stageReadResponseAlways();
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_3_whas____d203 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_3.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_2_whas____d195 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_2.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_1_whas____d194 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_1.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_cnt_finalAdd = (INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_1_whas____d194 || INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_2_whas____d195) || INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_3_whas____d203;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_cnt_finalAdd = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_cnt_finalAdd;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_cnt_finalAdd)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_cnt_finalAdd();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_s1__dreg_update)
	   INST_top.INST_buf1.RL_bram_serverAdapterB_s1__dreg_update();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_writeBRAM)
	   INST_top.INST_buf1.RL_writeBRAM();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways = INST_top.INST_buf1.INST_bram_serverAdapterA_writeWithResp.METH_whas();
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_accum_accumulate)
	   INST_top.INST_buf1.RL_accum_accumulate();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_stageReadResponseAlways();
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_3_whas____d202 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_3.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_2_whas____d189 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_2.METH_whas();
	 INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_1_whas____d188 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_1.METH_whas();
	 INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_cnt_finalAdd = (INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_1_whas____d188 || INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_2_whas____d189) || INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_3_whas____d202;
	 INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_cnt_finalAdd = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_cnt_finalAdd;
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_cnt_finalAdd)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_cnt_finalAdd();
	 if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_s1__dreg_update)
	   INST_top.INST_buf1.RL_bram_serverAdapterA_s1__dreg_update();
	 if (INST_top.INST_mhrcv.DEF_WILL_FIRE_RL_moveMessage)
	   INST_top.INST_mhrcv.RL_moveMessage();
	 if (INST_top.INST_mhrcv.DEF_WILL_FIRE_RL_rcvHeader)
	   INST_top.INST_mhrcv.RL_rcvHeader();
	 if (INST_top.INST_mhsnd.DEF_WILL_FIRE_RL_sndHead)
	   INST_top.INST_mhsnd.RL_sndHead();
	 if (INST_top.INST_mhsnd.DEF_WILL_FIRE_RL_sndMesg)
	   INST_top.INST_mhsnd.RL_sndMesg();
	 if (INST_top.INST_mhsnd.DEF_WILL_FIRE_RL_popMhV)
	   INST_top.INST_mhsnd.RL_popMhV();
	 if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_1)
	   INST_top.RL_mkConnectionGetPut_1();
	 INST_top.INST_chk_cmpMatch_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_chk_cmpEOP_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_chk_cmpFire_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_s1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterB_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_s1_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_serverAdapterA_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_memory.clkA((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_bram_memory.clkB((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_accum_acc_v2.clk((tUInt8)1u, (tUInt8)1u);
	 INST_top.INST_buf1.INST_accum_acc_v1.clk((tUInt8)1u, (tUInt8)1u);
	 if (do_reset_ticks(simHdl))
	 {
	   INST_top.INST_buf1.INST_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_mesgInF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_msgF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_countWrd.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_countRdReq.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_countRd.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_readAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_writeAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_accum_value.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_lenF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_newMsg.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterA_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterA_s1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterB_cnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_buf1.INST_bram_serverAdapterB_s1.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_mesgInF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_lengthF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_hp.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_fragLenCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_headerF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_messageF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_msgDoneF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhsnd.INST_lenR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_mesgInF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_msgF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_countWrd.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_countRdReq.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_countRd.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_readAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_writeAddr.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_hp.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_messageF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_length.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_mhrcv.INST_endHead.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen1_randomF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen1_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_patternV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_mesgLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_initV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_tmp.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_lfsr_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_seedLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_startLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_minLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen1_maxLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_mesgOutF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen2_randomF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_gen2_count.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_patternV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_mesgLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_initV.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_tmp.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_lfsr_r.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_seedLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_startLFSR.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_minLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_gen2_maxLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_buffF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_chk_incorrect.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_checkF.rst_tick_clk((tUInt8)1u);
	   INST_top.INST_chk_minLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_maxLen.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_mesgCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_wordCnt.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_buff.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_check.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_cmpFire.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_cmpEOP.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_chk_cmpMatch.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_cycleCounter.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_length.rst_tick__clk__1((tUInt8)1u);
	   INST_top.INST_s2rF.rst_tick_clk((tUInt8)1u);
	 }
       };

/* Model creation/destruction functions */

void MODEL_mkFTop_dp705::create_model(tSimStateHdl simHdl, bool master)
{
  sim_hdl = simHdl;
  init_reset_request_counters(sim_hdl);
  mkFTop_dp705_instance = new MOD_mkFTop_dp705(sim_hdl, "top", NULL);
  bk_get_or_define_clock(sim_hdl, "CLK");
  if (master)
  {
    bk_alter_clock(sim_hdl, bk_get_clock_by_name(sim_hdl, "CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
    bk_use_default_reset(sim_hdl);
  }
  bk_set_clock_event_fn(sim_hdl,
			bk_get_clock_by_name(sim_hdl, "CLK"),
			schedule_posedge_CLK,
			NULL,
			(tEdgeDirection)(POSEDGE));
  (mkFTop_dp705_instance->INST_gen1_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_gen1_randomF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_gen2_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_gen2_randomF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_buffF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_checkF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_cmpFire_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_cmpEOP_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_chk_cmpMatch_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_mesgInF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_msgF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_accum_acc_v1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_accum_acc_v2.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_lenF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_memory.set_clk_1)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_memory.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outDataCore.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_enqData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_outData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_2.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_3.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_writeWithResp.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_s1_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outDataCore.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_enqData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_outData.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_2.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_3.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_writeWithResp.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_s1_1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_buf1.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhsnd.INST_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhsnd.INST_mesgInF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhsnd.INST_lengthF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhsnd.INST_headerF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhsnd.INST_messageF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhsnd.INST_msgDoneF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhsnd.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhrcv.INST_mesgOutF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhrcv.INST_mesgInF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhrcv.INST_msgF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhrcv.INST_messageF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_mhrcv.set_clk_0)("CLK");
  (mkFTop_dp705_instance->INST_s2rF.set_clk_0)("CLK");
  (mkFTop_dp705_instance->set_clk_0)("CLK");
}
void MODEL_mkFTop_dp705::destroy_model()
{
  delete mkFTop_dp705_instance;
  mkFTop_dp705_instance = NULL;
}
void MODEL_mkFTop_dp705::reset_model(bool asserted)
{
  (mkFTop_dp705_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
}
void * MODEL_mkFTop_dp705::get_instance()
{
  return mkFTop_dp705_instance;
}

/* Fill in version numbers */
void MODEL_mkFTop_dp705::get_version(unsigned int *year,
				     unsigned int *month,
				     char const **annotation,
				     char const **build)
{
  *year = 2012u;
  *month = 9u;
  *annotation = "beta1";
  *build = "29570";
}

/* Get the model creation time */
time_t MODEL_mkFTop_dp705::get_creation_time()
{
  
  /* Thu Oct 11 21:17:19 UTC 2012 */
  return 1349990239llu;
}

/* Control run-time licensing */
tUInt64 MODEL_mkFTop_dp705::skip_license_check()
{
  return 0llu;
}

/* State dumping function */
void MODEL_mkFTop_dp705::dump_state()
{
  (mkFTop_dp705_instance->dump_state)(0u);
}

/* VCD dumping functions */
MOD_mkFTop_dp705 & mkFTop_dp705_backing(tSimStateHdl simHdl)
{
  static MOD_mkFTop_dp705 *instance = NULL;
  if (instance == NULL)
  {
    vcd_set_backing_instance(simHdl, true);
    instance = new MOD_mkFTop_dp705(simHdl, "top", NULL);
    vcd_set_backing_instance(simHdl, false);
  }
  return *instance;
}
void MODEL_mkFTop_dp705::dump_VCD_defs()
{
  (mkFTop_dp705_instance->dump_VCD_defs)(vcd_depth(sim_hdl));
}
void MODEL_mkFTop_dp705::dump_VCD(tVCDDumpType dt)
{
  (mkFTop_dp705_instance->dump_VCD)(dt, vcd_depth(sim_hdl), mkFTop_dp705_backing(sim_hdl));
}
