/*
 * Generated by Bluespec Compiler, version 2012.09.beta1 (build 29570, 2012-09.11)
 * 
 * On Sun Oct  7 15:17:28 EDT 2012
 * 
 */

/* Generation options: keep-fires */
#ifndef __model_mkFTop_dp705_h__
#define __model_mkFTop_dp705_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

#include "bs_model.h"
#include "mkFTop_dp705.h"

/* Class declaration for a model of mkFTop_dp705 */
class MODEL_mkFTop_dp705 : public Model {
 
 /* Top-level module instance */
 private:
  MOD_mkFTop_dp705 *mkFTop_dp705_instance;
 
 /* Handle to the simulation kernel */
 private:
  tSimStateHdl sim_hdl;
 
 /* Constructor */
 public:
  MODEL_mkFTop_dp705();
 
 /* Functions required by the kernel */
 public:
  void create_model(tSimStateHdl simHdl, bool master);
  void destroy_model();
  void reset_model(bool asserted);
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build);
  time_t get_creation_time();
  void * get_instance();
  void dump_state();
  void dump_VCD_defs();
  void dump_VCD(tVCDDumpType dt);
  tUInt64 skip_license_check();
};

/* Function for creating a new model */
extern "C" {
  void * new_MODEL_mkFTop_dp705();
}

#endif /* ifndef __model_mkFTop_dp705_h__ */
