/*
 * Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
 * 
 * On Fri Oct  5 09:58:47 EDT 2012
 * 
 */
#include "bluesim_primitives.h"
#include "schedule.h"

#include <cstdlib>
#include <time.h>
#include "bluesim_kernel_api.h"
#include "bs_vcd.h"
#include "bs_reset.h"

#include "mkFTop_dp705.h"

namespace bluesim
{
  
  /* Top-level module instances */
  static MOD_mkFTop_dp705 *mkFTop_dp705_instance = NULL;
  
  
  /* Schedule functions */
  
  void schedule_posedge_CLK()
  {
    MOD_mkFTop_dp705 &INST_top = *mkFTop_dp705_instance;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d171;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d177;
    tUInt8 DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d198;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d165;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d172;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d196;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d199;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d167;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d168;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d166;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d178;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d197;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d200;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d173;
    tUInt8 DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d174;
    INST_top.INST_buf1.PORT_EN_sink_put = (tUInt8)0u;
    INST_top.INST_buf1.DEF_WILL_FIRE_sink_put = (tUInt8)0u;
    INST_top.INST_buf1.PORT_EN_src_get = (tUInt8)0u;
    INST_top.INST_buf1.DEF_WILL_FIRE_src_get = (tUInt8)0u;
    INST_top.DEF_CAN_FIRE_RL_chk_compare = INST_top.INST_chk_buffF.METH_i_notEmpty() && INST_top.INST_chk_checkF.METH_i_notEmpty();
    INST_top.DEF_WILL_FIRE_RL_chk_compare = INST_top.DEF_CAN_FIRE_RL_chk_compare;
    INST_top.DEF_CAN_FIRE_RL_cycleCount = (tUInt8)1u;
    INST_top.DEF_WILL_FIRE_RL_cycleCount = INST_top.DEF_CAN_FIRE_RL_cycleCount;
    INST_top.DEF_CAN_FIRE_RL_gen1_genMesg = INST_top.INST_gen1_mesgOutF.METH_i_notFull();
    INST_top.DEF_WILL_FIRE_RL_gen1_genMesg = INST_top.DEF_CAN_FIRE_RL_gen1_genMesg;
    INST_top.DEF_CAN_FIRE_RL_gen2_genMesg = INST_top.INST_gen2_mesgOutF.METH_i_notFull();
    INST_top.DEF_WILL_FIRE_RL_gen2_genMesg = INST_top.DEF_CAN_FIRE_RL_gen2_genMesg;
    INST_top.DEF_CAN_FIRE_RL_gobble = (tUInt8)1u;
    INST_top.DEF_WILL_FIRE_RL_gobble = INST_top.DEF_CAN_FIRE_RL_gobble;
    INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut = INST_top.INST_buf1.METH_RDY_sink_put() && INST_top.INST_gen1_mesgOutF.METH_i_notEmpty();
    INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut;
    INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_1 = INST_top.INST_buf1.METH_RDY_src_get() && INST_top.INST_chk_buffF.METH_i_notFull();
    INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_1 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_1;
    INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_2 = INST_top.INST_gen2_mesgOutF.METH_i_notEmpty() && INST_top.INST_chk_checkF.METH_i_notFull();
    INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_2 = INST_top.DEF_CAN_FIRE_RL_mkConnectionGetPut_2;
    INST_top.INST_buf1.DEF_bram_serverAdapterA_s1___d187 = INST_top.INST_buf1.INST_bram_serverAdapterA_s1.METH_read();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d172 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_notFull();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d171 = (tUInt8)((INST_top.INST_buf1.DEF_bram_serverAdapterA_s1___d187) >> 1u);
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_moveToOutFIFO = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d172 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d171;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_moveToOutFIFO = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_moveToOutFIFO;
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d199 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_i_notEmpty();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d165 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_notEmpty();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstCore = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d199 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d165;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstCore = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstCore;
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_overRun = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_s1_1_BIT_1___d171 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notFull____d172;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_overRun = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_overRun;
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_s1__dreg_update = (tUInt8)1u;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_s1__dreg_update = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_s1__dreg_update;
    INST_top.INST_buf1.DEF_bram_serverAdapterB_s1___d188 = INST_top.INST_buf1.INST_bram_serverAdapterB_s1.METH_read();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d178 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_notFull();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d177 = (tUInt8)((INST_top.INST_buf1.DEF_bram_serverAdapterB_s1___d188) >> 1u);
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_moveToOutFIFO = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d178 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d177;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_moveToOutFIFO = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_moveToOutFIFO;
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_s1_08_BIT_1___d177 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notFull____d178;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_overRun = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun;
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d200 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_i_notEmpty();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d166 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_notEmpty();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstCore = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d200 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d166;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstCore = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstCore;
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_s1__dreg_update = (tUInt8)1u;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_s1__dreg_update = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_s1__dreg_update;
    INST_top.INST_buf1.DEF_b__h2983 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt.METH_read();
    DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d198 = INST_top.INST_buf1.INST_msgF.METH_i_notEmpty();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_readReqBRAM = (DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d198 && primSLT8(1u,
														     3u,
														     (tUInt8)(INST_top.INST_buf1.DEF_b__h2983),
														     3u,
														     (tUInt8)3u)) && INST_top.INST_buf1.INST_msgF.METH_notEmpty();
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_readReqBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_readReqBRAM;
    INST_top.INST_buf1.DEF_b__h1584 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt.METH_read();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_writeBRAM = INST_top.INST_buf1.INST_mesgInF.METH_i_notEmpty() && (primSLT8(1u,
														  3u,
														  (tUInt8)(INST_top.INST_buf1.DEF_b__h1584),
														  3u,
														  (tUInt8)3u) && INST_top.INST_buf1.INST_msgF.METH_i_notFull());
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_writeBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_writeBRAM;
    if (INST_top.DEF_WILL_FIRE_RL_gobble)
      INST_top.RL_gobble();
    if (INST_top.DEF_WILL_FIRE_RL_cycleCount)
      INST_top.RL_cycleCount();
    if (INST_top.DEF_WILL_FIRE_RL_gen1_genMesg)
      INST_top.RL_gen1_genMesg();
    if (INST_top.DEF_WILL_FIRE_RL_gen2_genMesg)
      INST_top.RL_gen2_genMesg();
    if (INST_top.DEF_WILL_FIRE_RL_chk_compare)
      INST_top.RL_chk_compare();
    if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut)
      INST_top.RL_mkConnectionGetPut();
    if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_1)
      INST_top.RL_mkConnectionGetPut_1();
    if (INST_top.DEF_WILL_FIRE_RL_mkConnectionGetPut_2)
      INST_top.RL_mkConnectionGetPut_2();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_moveToOutFIFO)
      INST_top.INST_buf1.RL_bram_serverAdapterA_moveToOutFIFO();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d168 = INST_top.INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.METH_whas();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d167 = INST_top.INST_buf1.INST_bram_serverAdapterA_outData_enqData.METH_whas();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_deqOnly = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d199 && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d168 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d167);
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_deqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_deqOnly;
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d196 = INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.METH_i_notFull();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notEmpty____d199 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d196) && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d168 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d167);
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq;
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqOnly = DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_i_notFull____d196 && (!DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_deqCalled_whas____d168 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d167);
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_enqOnly;
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq = !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outDataCore_notEmpty____d165 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterA_outData_enqData_whas____d167;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq;
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstCore)
      INST_top.INST_buf1.RL_bram_serverAdapterA_outData_setFirstCore();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqAndDeq)
      INST_top.INST_buf1.RL_bram_serverAdapterA_outData_enqAndDeq();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_setFirstEnq)
      INST_top.INST_buf1.RL_bram_serverAdapterA_outData_setFirstEnq();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_enqOnly)
      INST_top.INST_buf1.RL_bram_serverAdapterA_outData_enqOnly();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_overRun)
      INST_top.INST_buf1.RL_bram_serverAdapterA_overRun();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_outData_deqOnly)
      INST_top.INST_buf1.RL_bram_serverAdapterA_outData_deqOnly();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_moveToOutFIFO)
      INST_top.INST_buf1.RL_bram_serverAdapterB_moveToOutFIFO();
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d173 = INST_top.INST_buf1.INST_bram_serverAdapterB_outData_enqData.METH_whas();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq = !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d166 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d173;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq;
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstCore)
      INST_top.INST_buf1.RL_bram_serverAdapterB_outData_setFirstCore();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq)
      INST_top.INST_buf1.RL_bram_serverAdapterB_outData_setFirstEnq();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_readBRAM = DEF_INST_top_INST_buf1_DEF_msgF_i_notEmpty____d198 && ((DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_notEmpty____d166 || DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d173) && (INST_top.INST_buf1.INST_mesgOutF.METH_i_notFull() && INST_top.INST_buf1.INST_bram_serverAdapterB_outData_outData.METH_whas()));
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_readBRAM = INST_top.INST_buf1.DEF_CAN_FIRE_RL_readBRAM;
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_overRun)
      INST_top.INST_buf1.RL_bram_serverAdapterB_overRun();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_readReqBRAM)
      INST_top.INST_buf1.RL_readReqBRAM();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways = INST_top.INST_buf1.INST_bram_serverAdapterB_writeWithResp.METH_whas();
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways;
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_stageReadResponseAlways)
      INST_top.INST_buf1.RL_bram_serverAdapterB_stageReadResponseAlways();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_s1__dreg_update)
      INST_top.INST_buf1.RL_bram_serverAdapterB_s1__dreg_update();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_readBRAM)
      INST_top.INST_buf1.RL_readBRAM();
    INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_3_whas____d185 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_3.METH_whas();
    INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_2_whas____d176 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_2.METH_whas();
    INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_1_whas____d175 = INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_1.METH_whas();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_cnt_finalAdd = (INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_1_whas____d175 || INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_2_whas____d176) || INST_top.INST_buf1.DEF_bram_serverAdapterB_cnt_3_whas____d185;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_cnt_finalAdd = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_cnt_finalAdd;
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d174 = INST_top.INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.METH_whas();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_deqOnly = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d200 && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d174 && !DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d173)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq);
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_deqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_deqOnly;
    DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d197 = INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.METH_i_notFull();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqOnly = (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d197 && (!DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d174 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d173)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun);
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqOnly = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqOnly;
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq = ((DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notEmpty____d200 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outDataCore_i_notFull____d197) && (DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_deqCalled_whas____d174 && DEF_INST_top_INST_buf1_DEF_bram_serverAdapterB_outData_enqData_whas____d173)) && !(INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_setFirstEnq || INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_overRun);
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq;
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_cnt_finalAdd)
      INST_top.INST_buf1.RL_bram_serverAdapterB_cnt_finalAdd();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_deqOnly)
      INST_top.INST_buf1.RL_bram_serverAdapterB_outData_deqOnly();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqAndDeq)
      INST_top.INST_buf1.RL_bram_serverAdapterB_outData_enqAndDeq();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterB_outData_enqOnly)
      INST_top.INST_buf1.RL_bram_serverAdapterB_outData_enqOnly();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_writeBRAM)
      INST_top.INST_buf1.RL_writeBRAM();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways = INST_top.INST_buf1.INST_bram_serverAdapterA_writeWithResp.METH_whas();
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways;
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_stageReadResponseAlways)
      INST_top.INST_buf1.RL_bram_serverAdapterA_stageReadResponseAlways();
    INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_3_whas____d183 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_3.METH_whas();
    INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_2_whas____d170 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_2.METH_whas();
    INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_1_whas____d169 = INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_1.METH_whas();
    INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_cnt_finalAdd = (INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_1_whas____d169 || INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_2_whas____d170) || INST_top.INST_buf1.DEF_bram_serverAdapterA_cnt_3_whas____d183;
    INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_cnt_finalAdd = INST_top.INST_buf1.DEF_CAN_FIRE_RL_bram_serverAdapterA_cnt_finalAdd;
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_cnt_finalAdd)
      INST_top.INST_buf1.RL_bram_serverAdapterA_cnt_finalAdd();
    if (INST_top.INST_buf1.DEF_WILL_FIRE_RL_bram_serverAdapterA_s1__dreg_update)
      INST_top.INST_buf1.RL_bram_serverAdapterA_s1__dreg_update();
    INST_top.INST_buf1.INST_bram_serverAdapterB_s1_1.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterB_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterB_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterB_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterB_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_s1_1.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_writeWithResp.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_3.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_2.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_cnt_1.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_outData_outData.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_serverAdapterA_outData_enqData.clk((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_memory.clkA((tUInt8)1u, (tUInt8)1u);
    INST_top.INST_buf1.INST_bram_memory.clkB((tUInt8)1u, (tUInt8)1u);
    if (do_reset_ticks())
    {
      INST_top.INST_buf1.INST_mesgOutF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_buf1.INST_mesgInF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_buf1.INST_wrF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_buf1.INST_msgF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_buf1.INST_countSeg.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_countRd.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_count.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_readAddr.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_writeAddr.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_bram_serverAdapterA_outDataCore.rst_tick_clk((tUInt8)1u);
      INST_top.INST_buf1.INST_bram_serverAdapterA_cnt.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_bram_serverAdapterA_s1.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_bram_serverAdapterB_outDataCore.rst_tick_clk((tUInt8)1u);
      INST_top.INST_buf1.INST_bram_serverAdapterB_cnt.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_buf1.INST_bram_serverAdapterB_s1.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen1_mesgOutF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_gen1_count.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen1_patternV.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen1_mesgLen.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen1_initV.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen1_tmp.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen2_mesgOutF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_gen2_count.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen2_patternV.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen2_mesgLen.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen2_initV.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_gen2_tmp.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_chk_buffF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_chk_incorrect.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_chk_checkF.rst_tick_clk((tUInt8)1u);
      INST_top.INST_chk_mesgCnt.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_chk_wordCnt.rst_tick__clk__1((tUInt8)1u);
      INST_top.INST_cycleCounter.rst_tick__clk__1((tUInt8)1u);
    }
  }
  
  /* Model creation/destruction functions */
  
  void create_model(bool master)
  {
    init_reset_request_counters();
    mkFTop_dp705_instance = new MOD_mkFTop_dp705("top", NULL);
    bk_get_or_define_clock("CLK");
    if (master)
    {
      bk_alter_clock(bk_get_clock_by_name("CLK"), CLK_LOW, false, 0llu, 5llu, 5llu);
      bk_use_default_reset();
    }
    bk_set_clock_event_fn(bk_get_clock_by_name("CLK"),
			  schedule_posedge_CLK,
			  NULL,
			  (tEdgeDirection)(POSEDGE));
    (mkFTop_dp705_instance->INST_gen1_mesgOutF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_gen2_mesgOutF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_chk_buffF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_chk_checkF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_mesgOutF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_mesgInF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_wrF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_msgF.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_memory.set_clk_1)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_memory.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outDataCore.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_enqData.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_outData.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_outData_deqCalled.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_1.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_2.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_cnt_3.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_writeWithResp.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterA_s1_1.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outDataCore.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_enqData.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_outData.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_outData_deqCalled.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_1.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_2.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_cnt_3.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_writeWithResp.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.INST_bram_serverAdapterB_s1_1.set_clk_0)("CLK");
    (mkFTop_dp705_instance->INST_buf1.set_clk_0)("CLK");
    (mkFTop_dp705_instance->set_clk_0)("CLK");
  }
  void destroy_model()
  {
    delete mkFTop_dp705_instance;
    mkFTop_dp705_instance = NULL;
  }
  void reset_model(bool asserted)
  {
    (mkFTop_dp705_instance->reset_RST_N)(asserted ? (tUInt8)0u : (tUInt8)1u);
  }
  void * get_instance()
  {
    return mkFTop_dp705_instance;
  }
  
  /* Fill in version numbers */
  void get_version(unsigned int *year,
		   unsigned int *month,
		   char const **annotation,
		   char const **build)
  {
    *year = 2012u;
    *month = 1u;
    *annotation = "A";
    *build = "26572";
  }
  
  /* Get the model creation time */
  time_t get_creation_time()
  {
    
    /* Fri Oct  5 13:58:47 UTC 2012 */
    return 1349445527llu;
  }
  
  /* Control run-time licensing */
  tUInt64 skip_license_check()
  {
    return 0llu;
  }
  
  /* State dumping function */
  void dump_state()
  {
    (mkFTop_dp705_instance->dump_state)(0u);
  }
  
  /* VCD dumping functions */
  MOD_mkFTop_dp705 & mkFTop_dp705_backing()
  {
    static MOD_mkFTop_dp705 *instance = NULL;
    if (instance == NULL)
    {
      vcd_set_backing_instance(true);
      instance = new MOD_mkFTop_dp705("top", NULL);
      vcd_set_backing_instance(false);
    }
    return *instance;
  }
  void dump_VCD_defs()
  {
    (mkFTop_dp705_instance->dump_VCD_defs)(vcd_depth);
  }
  void dump_VCD(tVCDDumpType dt)
  {
    (mkFTop_dp705_instance->dump_VCD)(dt, vcd_depth, mkFTop_dp705_backing());
  }
}
